services:
  db:
    image: mysql:8.0
    container_name: ProjectComplaint_DB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: Webdb
    ports:
      - "8821:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - complaint_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pROOT"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ProjectComplaint_Admin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ROOT
    ports:
      - "8822:80"
    depends_on:
      - db
    networks:
      - complaint_net
    restart: always

  backend:
    build: ./Backend
    container_name: ProjectComplaint_Backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - complaint_net

networks:
  complaint_net:
    driver: bridge

volumes:
  mysql_data:
