# 1. ใช้ Image หลักเป็น Node.js 
FROM node:18

# 2. กำหนดโฟลเดอร์ทำงานข้างในตู้คอนเทนเนอร์
WORKDIR /app

# 3. ก๊อปปี้ไฟล์รายชื่อ Library (package.json) มาวางก่อน
COPY package*.json ./

# 4. สั่งติดตั้ง Library ต่างๆ ที่ต้องใช้
RUN npm install

# 5. ก๊อปปี้โค้ดทั้งหมดให้ตามมาทีหลัง
COPY . .

# 6. บอกว่า App เราจะรันที่พอร์ต 8000
EXPOSE 8000

# 7. คำสั่งที่ใช้เริ่มรันโปรเจกต์
CMD ["node", "index.js"]